from __future__ import annotations

from typing import Any


def render_dev_judge_report(
    *,
    manifest: dict[str, Any],
    source_policy_summary: dict[str, Any],
    source_policy_shadow_summary: dict[str, Any],
    inject_quality_summary: dict[str, Any],
    strict_layer3_audit_summary: dict[str, Any],
    dataset_diff_summary: dict[str, Any],
    judge_backend_availability: dict[str, Any],
) -> str:
    lines = [
        "# Developer Judge Report",
        "",
        f"- run_id: `{manifest.get('run_id', '')}`",
        f"- created_at_utc: `{manifest.get('created_at', '')}`",
        f"- output_root: `{manifest.get('output_root', '')}`",
        f"- baseline_snapshot: `{manifest.get('baseline_snapshot_path', '')}`",
        f"- canonical_outputs_modified: `{bool(manifest.get('canonical_outputs_modified', False))}`",
        "",
        "## Backend Availability",
        f"- requested_backend: `{judge_backend_availability.get('requested_backend', '')}`",
        f"- expected_execution_mode: `{judge_backend_availability.get('expected_execution_mode', '')}`",
        f"- local_test_judge_enabled: `{bool(judge_backend_availability.get('local_test_judge_enabled', False))}`",
        f"- local_model_id: `{judge_backend_availability.get('local_model_id', '')}`",
        f"- local_model_present: `{bool(judge_backend_availability.get('local_model_present', False))}`",
        f"- local_model_path: `{judge_backend_availability.get('local_model_path', '')}`",
        f"- local_model_runtime_ready: `{bool(judge_backend_availability.get('local_model_runtime_ready', False))}`",
        f"- local_model_manifest_backend: `{judge_backend_availability.get('local_model_manifest_backend', '')}`",
        f"- local_model_status_reason: `{judge_backend_availability.get('local_model_status_reason', '')}`",
        f"- remote_test_judge_enabled: `{bool(judge_backend_availability.get('remote_test_judge_enabled', False))}`",
        f"- remote_provider: `{judge_backend_availability.get('remote_provider', '')}`",
        f"- remote_model_id: `{judge_backend_availability.get('remote_model_id', '')}`",
        f"- remote_credentials_configured: `{bool(judge_backend_availability.get('remote_credentials_configured', False))}`",
        "",
        "## Source Policy Audit",
        f"- rows_total: `{int(source_policy_summary.get('rows_total', 0))}`",
        f"- judged_rows: `{int(source_policy_summary.get('judged_rows', 0))}`",
        f"- skipped_rows: `{int(source_policy_summary.get('skipped_rows', 0))}`",
        f"- effective_backend_counts: `{source_policy_summary.get('effective_backend_counts', {})}`",
        f"- fallback_used_count: `{int(source_policy_summary.get('fallback_used_count', 0))}`",
        f"- segmentation_policy_counts: `{source_policy_summary.get('segmentation_policy_counts', {})}`",
        "",
        "## Source Policy Shadow Apply",
        f"- considered_rows: `{int(source_policy_shadow_summary.get('considered_rows', 0))}`",
        f"- applied_rows: `{int(source_policy_shadow_summary.get('applied_rows', 0))}`",
        f"- validation_failed_rows: `{int(source_policy_shadow_summary.get('validation_failed_rows', 0))}`",
        f"- generated_files: `{source_policy_shadow_summary.get('generated_files', [])}`",
        "",
        "## Inject Quality Audit",
        f"- rows_total: `{int(inject_quality_summary.get('rows_total', 0))}`",
        f"- judged_rows: `{int(inject_quality_summary.get('judged_rows', 0))}`",
        f"- skipped_rows: `{int(inject_quality_summary.get('skipped_rows', 0))}`",
        f"- effective_backend_counts: `{inject_quality_summary.get('effective_backend_counts', {})}`",
        f"- fallback_used_count: `{int(inject_quality_summary.get('fallback_used_count', 0))}`",
        f"- label_counts: `{inject_quality_summary.get('label_counts', {})}`",
        "",
        "## Strict Layer3 Audit",
        f"- status: `{strict_layer3_audit_summary.get('status', '')}`",
        f"- artifact_resolution: `{strict_layer3_audit_summary.get('artifact_resolution', {})}`",
        f"- artifacts: `{strict_layer3_audit_summary.get('artifacts', {})}`",
        f"- strict_layer3_gate: `{strict_layer3_audit_summary.get('strict_layer3_gate', {})}`",
        f"- false_positive_drift: `{strict_layer3_audit_summary.get('false_positive_drift', {})}`",
        f"- typed_inject_disagreement: `{strict_layer3_audit_summary.get('typed_inject_disagreement', {})}`",
        "",
        "## Baseline Diff",
        f"- compared_files: `{int(dataset_diff_summary.get('compared_files', 0))}`",
        f"- identical_files: `{int(dataset_diff_summary.get('identical_files', 0))}`",
        f"- changed_files: `{int(dataset_diff_summary.get('changed_files', 0))}`",
        f"- missing_in_canonical: `{int(dataset_diff_summary.get('missing_in_canonical', 0))}`",
    ]
    return "\n".join(lines) + "\n"
